apiVersion: v1
kind: Service
metadata:
  name: g73-payment-api-service
spec:
  selector:
    app: g73-payment-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30004
  type: LoadBalancer