paymentBroker:
  url: https://api.mercadopago.com/instore/orders/qr/seller/collectors/teste/pos/123/qrs
  notificationUrl: https://g37-lanches
  sponsorId: "12345"

paymentRepository:
  table: Payment
  endpoint: http://localhost:8000/